name: monalisa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Mona_Lisa.jpg
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Black.ttf
        - asset: fonts/Merriweather-BlackItalic.ttf
        - asset: fonts/Merriweather-Bold.ttf
        - asset: fonts/Merriweather-BoldItalic.ttf
        - asset: fonts/Merriweather-Italic.ttf
        - asset: fonts/Merriweather-Light.ttf
        - asset: fonts/Merriweather-LightItalic.ttf
        - asset: fonts/Merriweather-Regular.ttf
